### PR TITLE
Correct unit test with expected failure

### PR DESCRIPTION
**Pull request by rivercartwright**
The error returned by the SSL layer when hitting https://invalid-expected-sct.badssl.com/ has changed. An SSL handshake exception is thrown and must be caught and suppressed.

### CODE REVIEW

**Comment by rivercartwright** [comment]
Hi @djp3 would you please grant permission for your mods to be used once more?

**Comment by djp3** [comment]
I consent to having my code included in this project.

**Review by djp3 — APPROVED** [review]
I reviewed this code and think it looks ready to merge.

**Comment by AlCutter** [comment]
Just confirming here that `djp3` has signed CLA

**Comment by rivercartwright** [comment]
This PR has been open for a long time. Would someone please perform the review?

**Comment by AlCutter** [comment]
Ping @Martin2112

**Comment by Martin2112** [comment]
There still seems to be a problem with CLAs on this PR.

**Comment by rivercartwright** [comment]
What sort of problems? Both @djp3 and I have given consent. What more needs to be done?

**Comment by Martin2112** [comment]
It still says "unable to verify author consent". This is unfortunately an automatic process that runs behind the scenes.

**Comment by rivercartwright** [comment]
On 2018-12-04 (above) @djp3 wrote
"I consent to having my code included in this project."

How do we get the automated tool to accept this?

**Comment by Martin2112** [comment]
I'm not 100% sure why it hasn't been accepted. Could be something like signing the CLA with your work email address and committing with your github one. That's usually a different error message though.

If it's not something like that then we've confirmed that all contributors have signed so I can possibly review it anyway.

**Comment by Martin2112** [comment]
For the record I have verified that CLAs are on file for all the contributors to this PR.

**Comment by Martin2112** [comment]
I think this might be better as an example or integration test rather than a unit test. It seems to depend on servers being up and reachable, and not changing their certificates perhaps. 

Alternatively, could the server cert responses just be embedded in the test? Then it would be deterministic.

**Comment by mhutchinson** [comment]
Closing this Pull Request. This repo is no longer being maintained. See the README for info.

**Pull request closed without merging**
