### PR TITLE
maven central requirements

### PR DESCRIPTION
**Pull request by alexanderkjall**
I went over these guides http://central.sonatype.org/pages/requirements.html and http://central.sonatype.org/pages/apache-maven.html and added what was required getting the project accepted into maven central.

Someone also needs to apply for an account at OSSRH as described here: http://central.sonatype.org/pages/ossrh-guide.html .

I also added a -SNAPSHOT to the version, this is a magic word for maven that tells it that it's not a release that is being built. My thought was that when we want to release a new version, we branch the repo, remove the -SNAPSHOT and upload that.

The javadoc step adds some warnings about javadoc problems, I think those can be cleaned up in a separate commit?

### CODE REVIEW

**Comment by codingllama** [comment]
Hey Alexander, sorry for the delay. I won't be able to have a look today, but I'll try to do at least a first pass early next week.

**Comment by alexanderkjall** [comment]
I can submit a request to OSSRH, it will be the first time I do this myself, so it will be a good learning experience.

**Comment by codingllama** [comment]
Thanks for the changes, Alexander.

About OSSRH, I think one of the open source owners should do it. I'd also like to run it by our tech lead before signing in, have a look at the T&C, etc. Unfortunately a few people are on vacation this week, including our TL, so I'll ask you to wait for about a week on it.

Raised #9.

**Comment by alexanderkjall** [comment]
I agree that it's better if one of the owners do it. I would recommend some sort of system so that the same gpg key is used to sign all builds going forward. That makes it easier for people to verify the integrity of the builds.

**Pull request merged**
