### PR TITLE
Add example ssl connection check (#1)

### PR DESCRIPTION
**Pull request by rivercartwright**
Add a unit test that serves as an example of how to use certificate transparency to validate SSL connections.

### CODE REVIEW

**Comment by rivercartwright** [comment]
Fixes #26

**Comment by djp3** [comment]
I consent to including my code in this project

**Comment by djp3** [comment]
If it's not clear, this pull request is superseded by #30 after a certificate on badssl.com expired and can't reasonably be fixed.

**Comment by Martin2112** [comment]
So we close this one and #30 is the right one?

**Comment by rivercartwright** [comment]
Yes please.

**Comment by rivercartwright** [comment]
Closing this PR

**Pull request closed without merging**
